Rails:
  Enabled: true
AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*.rb'
    - 'config/**/*.rb'
    - 'spec/**/*.rb'
    - 'lib/tasks/*.rake'
  TargetRubyVersion: 2.4
Metrics/LineLength:
  Max: 110
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Lint/SymbolArray:
  Enabled: false
Metrics/ClassLength:
  Max: 250
Metrics/ModuleLength:
  Max: 250
Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Max: 50
